apiVersion: v1
kind: Pod
metadata:
  name: rgb-nagios-filter
spec:
  containers:
  - name: rgb-nagios-filter
    image: mmaschenk/rgb-nagios-filter:1.0
#    command: [ 'sleep' ]
#    args: [ "3600" ]
    envFrom:
    - secretRef:
        name: passwords
    - configMapRef:
        name: environment
