apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rgb-nagios-filter
  name: rgb-nagios-filter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rgb-nagios-filter
  template:
    metadata:
      labels:
        app: rgb-nagios-filter
    spec:
      containers:
      - name: rgb-nagios-filter
        image: ghcr.io/mmaschenk/docker-rgb-nagios-filter:1.4.3a
        envFrom:
        - secretRef:
            name: passwords
        - configMapRef:
            name: rgb-environment
